language: python

# python 3.7 workaround for travis
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

python:
  - 3.7


install:
  - pip install -r requirements.txt

script:
  - python app-test.py